import mssql from 'mssql';
import { Config } from '../utils/config.js';

export class SqlService {
  constructor() {
    this.config = Config.sql;
    this.pool = null;
  }

  /**
   * Get or initialize the active connection pool with auto-reconnect
   */
  async getPool() {
    if (!this.config) {
      throw new Error('SQL Configuration is missing. Please check your DB_CONNECTION_STRING or DB parameters in .env.');
    }

    try {
      if (!this.pool || !this.pool.connected) {
        if (this.pool) {
          await this.pool.close().catch(() => {});
        }

        const poolConfig = {
          ...this.config,
          requestTimeout: 20000, // 20 seconds timeout for complex queries/joins
          connectionTimeout: 15000,
          options: {
            ...this.config.options,
            trustServerCertificate: true, // Useful for self-signed certificates in local/dev DBs
            encrypt: false // SAP B1 local SQL usually doesn't strictly enforce encryption unless configured
          }
        };

        this.pool = await new mssql.ConnectionPool(poolConfig).connect();
        
        // Handle unexpected pool errors gracefully
        this.pool.on('error', (err) => {
          console.error('⚠️ SQL Pool Background Error:', err.message);
          this.pool = null;
        });
      }
      return this.pool;
    } catch (err) {
      this.pool = null;
      throw new Error(`Failed to connect to SQL Server: ${err.message}`);
    }
  }

  /**
   * Healthcheck endpoint for testing DB connectivity
   */
  async healthCheck() {
    try {
      const pool = await this.getPool();
      const result = await pool.request().query('SELECT 1 AS status');
      return result.recordset.length > 0 && result.recordset[0].status === 1;
    } catch (err) {
      console.error('❌ SQL Health Check Failed:', err.message);
      return false;
    }
  }

  /**
   * Cleans hallucinated syntax, code blocks, or procedure execution wrappers from raw LLM query
   */
  cleanIncomingQuery(rawQuery) {
    if (!rawQuery || typeof rawQuery !== 'string') return '';

    let q = rawQuery.trim();

    // 1. Strip Markdown code blocks if present (```sql ... ```)
    q = q.replace(/^```(?:sql)?/gi, '').replace(/```$/gi, '').trim();

    // 2. Fix hallucinated EXECUTE / Stored Procedure wrappers
    if (/^EXEC(?:UTE)?\s+/i.test(q)) {
      q = q.replace(/^EXEC(?:UTE)?\s+/i, '');
      q = q.replace(/^dbo\.execute_sql_query\s*\(/i, '');
      q = q.replace(/^['"]|['"]\s*\)?$/g, '');
    }

    // 3. Remove trailing semicolons for clean dynamic execution
    q = q.replace(/;+\s*$/, '');

    return q.trim();
  }

  /**
   * Execute read-only T-SQL queries generated by AI with SAP safeguards
   */
  async query(sqlText) {
    if (!sqlText || typeof sqlText !== 'string') {
      throw new Error('Query parameter must be a non-empty string.');
    }

    const cleanSql = this.cleanIncomingQuery(sqlText);
    const uppercaseSql = cleanSql.toUpperCase();
    
    // Forbidden modification keywords (Strict READ-ONLY policy)
    const forbiddenKeywords = [
      'INSERT', 'UPDATE', 'DELETE', 'DROP', 'ALTER', 
      'TRUNCATE', 'CREATE', 'GRANT', 'REVOKE', 'EXEC', 'EXECUTE'
    ];

    // Security Validation 1: Must start with SELECT or WITH (CTEs)
    if (!uppercaseSql.startsWith('SELECT') && !uppercaseSql.startsWith('WITH')) {
      throw new Error('Security Violation: Only READ-ONLY SELECT or WITH queries are permitted.');
    }

    // Security Validation 2: Check forbidden keywords using exact word boundaries
    const hasForbidden = forbiddenKeywords.some(kw => new RegExp(`\\b${kw}\\b`, 'i').test(uppercaseSql));
    if (hasForbidden) {
      throw new Error('Security Violation: Query contains forbidden modification or execution keywords.');
    }

    // Security Validation 3: Prevent SELECT ... INTO to prevent table creation
    if (/\bSELECT\b[\s\S]*?\bINTO\b/i.test(uppercaseSql)) {
      throw new Error('Security Violation: SELECT INTO operations are not permitted.');
    }

    try {
      const pool = await this.getPool();
      const request = pool.request();
      request.timeout = 20000; 

      const result = await request.query(cleanSql);
      return result.recordset || [];
    } catch (err) {
      console.error('❌ Direct SQL Execution Error:', err.message);
      throw new Error(`Database execution error: ${err.message} [Executed SQL: ${cleanSql}]`);
    }
  }

  /**
   * Gracefully close connection on server shutdown
   */
  async close() {
    if (this.pool) {
      await this.pool.close().catch(() => {});
      this.pool = null;
    }
  }
}